encoder_type: LSTM
decoder_type: FC
encoder_params:
  input_size: 21
  hidden_size: 64
  num_layers: 2
  bidirectional: true
decoder_params:
  window_size: 14
  horizon: 1
  input_size: 21
decoder_use_all_hidden: true
teacher_forcing_ratio: 0.0
learning_rate: 0.001
input_size: 21
optimizer_params: {}
lr_scheduler_params: {}
lr_scheduler: null
